[package]
name = "beep-boop"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
cpal = "0.15.3"
crossterm = "0.28.1"
rand = "0.8.5"
ratatui = "0.29.0"
ringbuf = "0.4.7"
soundio = "0.2.1"
