[package]
name = "beep-boop"
version = "0.1.0"
edition = "2021"

[dependencies]
audioviz = "0.6.0"
color-eyre = "0.6.3"
cpal = "0.15.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
ringbuf = "0.4.7"
chrono = "0.4.38"
lrc = "0.1.8"
timer = "0.2.0"
